import { useEffect, useState } from 'react';
import { api } from './api';

type Tx = { title: string; meta: string; amount: string; direction: 'in' | 'out' };
const transactions: Tx[] = [
  { title: 'Wallet deposit', meta: 'Today · Completed', amount: '+GH₵2,000.00', direction: 'in' },
  { title: 'Bet settlement', meta: 'Today · Sportsbook', amount: '+GH₵420.00', direction: 'in' },
  { title: 'Bet stake', meta: 'Yesterday · Premier League', amount: '-GH₵50.00', direction: 'out' },
  { title: 'Cash withdrawal', meta: '18 Sep · Completed', amount: '-GH₵800.00', direction: 'out' },
];

function ActionButton({ icon, label, primary, onClick }: { icon: string; label: string; primary?: boolean; onClick: () => void }) {
  return <button className={`wallet-action ${primary ? 'wallet-action-primary' : ''}`} onClick={onClick}><span className="material-symbols-rounded">{icon}</span>{label}</button>;
}

export default function AccountPage() {
  const [balance, setBalance] = useState('GH₵24,850.00');
  const [hideBalance, setHideBalance] = useState(false);
  const [message, setMessage] = useState('');
  useEffect(() => { api<any>('GET', '/api/wallet').then((data) => { const value = data?.balance ?? data?.wallet?.balance ?? data?.availableBalance; if (value !== undefined) setBalance(`GH₵${Number(value).toLocaleString('en-GH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`); }).catch(() => undefined); }, []);
  const notify = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(''), 2200); };
  return <section className="account-page glass-account-page">
    <div className="account-breadcrumb"><span>MY ACCOUNT</span><b>/</b> WALLET</div>
    <div className="account-heading"><div><small>ACCOUNT CENTER / BALANCE & PAYMENTS</small><h1>Your wallet, at a glance.</h1><p>Manage your balance, move funds, and keep track of every wallet activity from one secure account page.</p></div><div className="member-chip"><span className="member-avatar">LP</span><span><b>Lucky Player</b><small>Gold member · since 2024</small></span><span className="material-symbols-rounded">expand_more</span></div></div>
    <div className="wallet-layout"><div className="wallet-main-column"><section className="wallet-panel wallet-surface"><div className="wallet-panel-head"><div><small>SELECTED WALLET DIRECTION</small><h2>Glass Black</h2><p>Quiet luxury with a balance-first account view.</p></div><button className="wallet-icon-button" onClick={() => notify('Card options coming soon')}><span className="material-symbols-rounded">more_horiz</span></button></div>
      <div className="glass-wallet-card"><div className="glass-card-top"><b>LUCKYSTAKE <em>WALLET</em></b><span className="material-symbols-rounded">more_horiz</span></div><div className="glass-chip"><span></span><span></span><span></span><span></span></div><div className="glass-card-number">5421&nbsp;&nbsp; 8920&nbsp;&nbsp; 4712&nbsp;&nbsp; 0834</div><div className="glass-card-balance"><strong><span className="balance-currency">GH₵</span>{balance.replace('GH₵', '')}</strong></div><div className="glass-card-bottom"><span><small>CARD HOLDER</small><b>LUCKY PLAYER</b></span><span><small>VALID THRU</small><b>12/28</b></span><strong className="visa-mark">VISA</strong></div></div>
      <div className="wallet-balance-row"><span><small>AVAILABLE BALANCE</small><strong>{hideBalance ? <><span className="balance-currency">GH₵</span> ••••••</> : <><span className="balance-currency">GH₵</span>{balance.replace('GH₵', '')}</>}</strong><em>Nigeria · NGN wallet · •••• 0834</em></span><button onClick={() => setHideBalance(!hideBalance)}><span className="material-symbols-rounded">{hideBalance ? 'visibility' : 'visibility_off'}</span>{hideBalance ? 'Show' : 'Hide'} balance</button></div>
      <div className="wallet-actions"><ActionButton icon="add" label="Deposit" primary onClick={() => notify('Deposit flow opened')} /><ActionButton icon="south_west" label="Withdraw" onClick={() => notify('Withdrawal flow opened')} /><ActionButton icon="swap_horiz" label="Transfer" onClick={() => notify('Transfer flow opened')} /><ActionButton icon="more_horiz" label="More" onClick={() => notify('More wallet actions')} /></div></section>
      <div className="wallet-security"><span className="material-symbols-rounded">lock</span><span><b>Your wallet is protected</b><small>Two-step verification is active. All deposits and withdrawals are reviewed securely.</small></span><button onClick={() => notify('Security settings opened')}>Manage security <span className="material-symbols-rounded">arrow_outward</span></button></div></div>
      <aside className="wallet-side-column"><section className="wallet-panel wallet-surface"><div className="wallet-panel-head"><div><small>ACCOUNT SNAPSHOT</small><h2>This month</h2></div><span className="material-symbols-rounded wallet-lime-icon">trending_up</span></div><div className="wallet-stat-grid"><span><small>Total deposited</small><b>GH₵8,420.00</b><em>+14.8%</em></span><span><small>Total staked</small><b>GH₵3,180.00</b><em>+8.2%</em></span><span><small>Net winnings</small><b>GH₵1,260.00</b><em>+22.4%</em></span><span><small>Available bonus</small><b>GH₵250.00</b><em>Active</em></span></div><button className="wallet-text-link" onClick={() => notify('Statement opened')}>View monthly statement <span className="material-symbols-rounded">arrow_outward</span></button></section>
      <section className="wallet-panel wallet-surface"><div className="wallet-panel-head"><div><small>PAYMENT METHODS</small><h2>Saved methods</h2></div><button className="wallet-add-button" onClick={() => notify('Add payment method opened')}><span className="material-symbols-rounded">add</span> Add</button></div><div className="wallet-method"><b className="method-mark">M</b><span><b>Mastercard ·••• 7421</b><small>Primary · Expires 08/28</small></span><em>Verified</em></div><div className="wallet-method"><b className="method-mark mobile-mark"><span className="material-symbols-rounded">smartphone</span></b><span><b>MTN Mobile Money</b><small>+233 24 555 0192</small></span><em>Verified</em></div></section></aside></div>
    <div className="wallet-lower-grid"><section className="wallet-panel wallet-surface wallet-activity"><div className="wallet-panel-head"><div><small>WALLET ACTIVITY</small><h2>Recent transactions</h2></div><button className="wallet-text-link" onClick={() => notify('Transaction history opened')}>View all <span className="material-symbols-rounded">arrow_outward</span></button></div><div className="wallet-filters"><button className="active">All activity</button><button>Deposits</button><button>Withdrawals</button><button>Sportsbook</button></div>{transactions.map((tx) => <div className="wallet-transaction" key={tx.title}><span className={`tx-mark ${tx.direction}`}><span className="material-symbols-rounded">{tx.direction === 'in' ? 'south_west' : 'north_east'}</span></span><span><b>{tx.title}</b><small>{tx.meta}</small></span><strong className={tx.direction}>{tx.amount}</strong><span className="material-symbols-rounded tx-more">more_horiz</span></div>)}</section><section className="wallet-panel wallet-surface responsible-wallet"><span className="material-symbols-rounded">verified_user</span><small>PLAY WITH CONTROL</small><h2>Responsible play</h2><p>Set a personal deposit limit, take a break, or review your activity whenever you need.</p><button onClick={() => notify('Responsible play tools opened')}>Open tools <span className="material-symbols-rounded">arrow_outward</span></button></section></div>
    {message && <div className="wallet-toast"><span className="material-symbols-rounded">check_circle</span>{message}</div>}
  </section>;
}
