export const DEFAULT_API = 'https://futballbackend-production-15ee.up.railway.app';
const browserHost = typeof window === 'undefined' ? '' : window.location.hostname;
const useLocalProxy = import.meta.env.DEV && !/^(localhost|127\.0\.0\.1)$/.test(browserHost);
export const API_BASE = () => localStorage.getItem('luckystakeApiBaseUrl') || (useLocalProxy ? '' : DEFAULT_API);

export class ApiError extends Error { constructor(message: string, public status = 0) { super(message); } }
function token() { return localStorage.getItem('accessToken') || localStorage.getItem('token') || localStorage.getItem('authToken') || ''; }
export function setToken(value: string) { if (value) localStorage.setItem('accessToken', value); else localStorage.removeItem('accessToken'); }
export function setApiBase(value: string) { localStorage.setItem('luckystakeApiBaseUrl', value.replace(/\/$/, '')); }

export async function api<T>(method: string, path: string, body?: unknown): Promise<T> {
  const res = await fetch(`${API_BASE().replace(/\/$/, '')}${path}`, { method, credentials: 'include', headers: { Accept: 'application/json', ...(body === undefined ? {} : { 'Content-Type': 'application/json' }), ...(token() ? { Authorization: `Bearer ${token()}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await res.text(); let payload: unknown; try { payload = text ? JSON.parse(text) : undefined; } catch { payload = text; }
  if (!res.ok) { const p = payload as Record<string, unknown> | null; throw new ApiError(String(p?.message || p?.error || p?.detail || `Request failed (${res.status})`), res.status); }
  if (payload && typeof payload === 'object' && 'success' in payload && 'data' in payload) return (payload as { data: T }).data;
  return payload as T;
}

export type Feed = 'today' | 'upcoming' | 'live' | 'results';
export type Sport = 'football' | 'basketball' | 'nfl' | 'baseball' | 'mma' | 'tennis';
export type MatchRow = {
  id: string; homeTeam: string; awayTeam: string; league?: string; kickoffAt?: string; status?: string;
  source?: string; sport?: Sport; featured?: boolean; isAdmin?: boolean; minutePlayed?: number;
  scoreHome?: number; scoreAway?: number; homeLogo?: string; awayLogo?: string; displayHomeLogo?: string; displayAwayLogo?: string;
  homeOdds?: string; drawOdds?: string; awayOdds?: string;
  odds?: Array<{ selection?: string; odd?: string | number; value?: string | number; price?: string | number }>;
};

export const LIVE_STATUSES = new Set(['LIVE','IN_PLAY','INPLAY','IN_PROGRESS','PLAYING','FIRST_HALF','SECOND_HALF','HALFTIME','HALF_TIME','HT','EXTRA_TIME','ET','OVERTIME','OT','PENALTIES','PEN','SHOOTOUT','BREAK','SUSPENDED','INTERRUPTED','DELAYED','1ST_HALF','2ND_HALF','1H','2H','Q1','Q2','Q3','Q4','SET1','SET2','SET3','SET4','SET5']);
export const FINISHED_STATUSES = new Set(['FINISHED','FULL_TIME','FT','AWARDED','CANCELLED','CANCELED','POSTPONED','ABANDONED','VOID','ENDED','COMPLETED','COMPLETE','STATUS_FINAL','STATUS_FULL_TIME','STATUS_POSTPONED','STATUS_CANCELED']);
const normalizedStatus = (status?: string) => String(status || '').trim().toUpperCase().replace(/[\s-]+/g, '_');
export function isLiveStatus(status?: string) { const s = normalizedStatus(status); return LIVE_STATUSES.has(s) || /^(LIVE|IN_PLAY|IN_PROGRESS|1ST|2ND|3RD|4TH|HALF|HT|ET|OT|PEN|Q[1-4]|SET[1-5])/.test(s); }
export function isFinishedStatus(status?: string) { return FINISHED_STATUSES.has(normalizedStatus(status)); }
export function isFinishedMatch(match: MatchRow) { if (isFinishedStatus(match.status)) return true; const at = parseKickoff(match.kickoffAt); return !isLiveStatus(match.status) && Boolean(at && !Number.isNaN(at.getTime()) && Date.now() - at.getTime() > 3 * 60 * 60 * 1000 && match.scoreHome != null && match.scoreAway != null); }
function parseNumber(value: unknown) { const n = typeof value === 'number' ? value : Number(value); return Number.isFinite(n) ? n : undefined; }
export function parseKickoff(value?: string) { const date = value ? new Date(value) : new Date(NaN); return date; }
export function formatKickoffDate(value?: string) { const date = parseKickoff(value); if (Number.isNaN(date.getTime())) return ''; const key = (d: Date) => d.toLocaleDateString('en-CA'); const now = new Date(); if (key(date) === key(now)) return 'Today'; const tomorrow = new Date(now.getTime() + 86400000); if (key(date) === key(tomorrow)) return 'Tomorrow'; return date.toLocaleDateString([], { day: '2-digit', month: 'short' }); }
export function formatKickoff(value?: string) { const date = parseKickoff(value); return Number.isNaN(date.getTime()) ? '—:—' : date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false }); }
export function liveClock(match: MatchRow) { const status = normalizedStatus(match.status); if (status === 'HALFTIME' || status === 'HT') return 'HT'; if (status === 'PENALTIES' || status === 'PEN') return 'PEN'; if (status === 'EXTRA_TIME' || status === 'ET' || status === 'OVERTIME' || status === 'OT') return 'ET'; if (match.minutePlayed != null) return `${match.minutePlayed}'`; const kickoff = parseKickoff(match.kickoffAt).getTime(); if (Number.isNaN(kickoff)) return 'LIVE'; const mins = Math.max(1, Math.floor((Date.now() - kickoff) / 60000)); return mins <= 45 ? `${mins}'` : mins <= 60 ? 'HT' : `${Math.min(90, 45 + mins - 60)}'`; }

function safeLogo(value: unknown) { const logo = String(value || '').trim(); return logo && !logo.startsWith('blob:') && !logo.startsWith('data:') ? logo : ''; }
function initials(name: string) { const words = name.trim().split(/\s+/).filter(Boolean); return (words.length > 1 ? words[0][0] + words[words.length - 1][0] : words[0]?.slice(0, 2) || '?').toUpperCase(); }
export function generatedCrest(name: string) { let hash = 0; for (const char of name.toLowerCase()) hash = (hash * 31 + char.charCodeAt(0)) >>> 0; const palette = [['#7444c5','#3f1d75'],['#d6ee46','#78861b'],['#2f6fd6','#123b78'],['#0b6e4f','#043a2c'],['#c04b78','#5b1f42']][hash % 5]; const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${palette[0]}"/><stop offset="1" stop-color="${palette[1]}"/></linearGradient></defs><circle cx="32" cy="32" r="30" fill="url(#g)"/><text x="32" y="32" fill="#fff" font-family="Arial" font-size="${initials(name).length > 2 ? 17 : 20}" font-weight="800" text-anchor="middle" dominant-baseline="central">${initials(name)}</text></svg>`; return `data:image/svg+xml,${encodeURIComponent(svg)}`; }
export function fallbackCrest(name: string, side: 'home' | 'away' = 'home') { let hash = 0; for (const char of `${name.toLowerCase()}:${side}`) hash = (hash * 31 + char.charCodeAt(0)) >>> 0; const folder = side === 'away' ? 'team-away' : 'team-home'; const index = String((hash % 20) + 1).padStart(2, '0'); return `/admin-logos/${folder}-${index}.png`; }
function nestedLogo(value: unknown): string { if (!value || typeof value !== 'object') return ''; const obj = value as Record<string, unknown>; const flat = safeLogo(obj.logo ?? obj.logoUrl ?? obj.logo_url ?? obj.crest ?? obj.badge ?? obj.image); if (flat) return flat; if (Array.isArray(obj.logos)) { for (const entry of obj.logos) { const found = nestedLogo(entry); if (found) return found; } } return nestedLogo(obj.team); }
function findOdd(odds: MatchRow['odds'], choices: string[]) { const found = (odds || []).find(item => choices.includes(String(item.selection || '').trim().toLowerCase())); return found ? String(found.odd ?? found.value ?? found.price ?? '') : ''; }
function normalizeMatch(entry: unknown, sport: Sport): MatchRow | null { if (!entry || typeof entry !== 'object') return null; const outer = entry as Record<string, unknown>; const raw = outer.match && typeof outer.match === 'object' ? outer.match as Record<string, unknown> : outer; const id = String(raw.id ?? raw.matchId ?? raw.match_id ?? raw.backendId ?? raw.uuid ?? raw.eventId ?? ''); if (!id) return null; const competitors = Array.isArray(raw.competitors) ? raw.competitors as Record<string, unknown>[] : []; const homeComp = competitors.find(c => String(c.homeAway ?? c.type).toLowerCase() === 'home') || competitors[0]; const awayComp = competitors.find(c => String(c.homeAway ?? c.type).toLowerCase() === 'away') || competitors[1]; const homeObj = (raw.home && typeof raw.home === 'object' ? raw.home : homeComp?.team && typeof homeComp.team === 'object' ? homeComp.team : homeComp) as Record<string, unknown> | undefined; const awayObj = (raw.away && typeof raw.away === 'object' ? raw.away : awayComp?.team && typeof awayComp.team === 'object' ? awayComp.team : awayComp) as Record<string, unknown> | undefined; const homeTeam = String(raw.homeTeam ?? raw.home_team ?? raw.homeName ?? homeObj?.name ?? homeObj?.displayName ?? 'Home'); const awayTeam = String(raw.awayTeam ?? raw.away_team ?? raw.awayName ?? awayObj?.name ?? awayObj?.displayName ?? 'Away'); const odds = Array.isArray(outer.odds) ? outer.odds as MatchRow['odds'] : Array.isArray(outer.match_result) ? outer.match_result as MatchRow['odds'] : []; const homeLogo = nestedLogo(homeObj) || safeLogo(raw.homeLogo ?? raw.home_logo); const awayLogo = nestedLogo(awayObj) || safeLogo(raw.awayLogo ?? raw.away_logo); const scoreHome = parseNumber(raw.scoreHome ?? raw.score_home ?? raw.homeScore ?? homeComp?.score ?? homeObj?.score); const scoreAway = parseNumber(raw.scoreAway ?? raw.score_away ?? raw.awayScore ?? awayComp?.score ?? awayObj?.score); const row: MatchRow = { id, homeTeam, awayTeam, league: String(raw.league ?? raw.leagueName ?? raw.competition ?? 'Match'), kickoffAt: String(raw.kickoffAt ?? raw.kickoff_at ?? raw.startTime ?? raw.date ?? ''), status: String(raw.status ?? raw.matchStatus ?? ''), source: String(raw.source ?? ''), sport, featured: Boolean(raw.featured ?? raw.isFeatured), isAdmin: Boolean(raw.isAdmin) || String(raw.source ?? '').toUpperCase() === 'ADMIN_CREATED', minutePlayed: parseNumber(raw.minutePlayed ?? raw.minute_played), scoreHome, scoreAway, homeLogo, awayLogo, odds, homeOdds: findOdd(odds, [homeTeam.toLowerCase(), 'home', '1']), drawOdds: findOdd(odds, ['draw', 'x']), awayOdds: findOdd(odds, [awayTeam.toLowerCase(), 'away', '2']) }; const adminMatch = row.isAdmin || row.featured; row.displayHomeLogo = adminMatch ? (row.homeLogo || fallbackCrest(homeTeam, 'home')) : row.homeLogo; row.displayAwayLogo = adminMatch ? ((!row.awayLogo || row.awayLogo === row.displayHomeLogo) ? fallbackCrest(awayTeam, 'away') : row.awayLogo) : row.awayLogo; return row; }
const VISUALLY_DUPLICATE_AWAY_BY_HOME: Record<number, number[]> = { 2: [14], 5: [9, 10, 17], 7: [12], 12: [1, 9, 10, 17], 13: [2], 17: [14], 19: [16], 20: [1, 17] }; function distinctCrest(name: string, side: 'home' | 'away', used: Set<string>, avoidHome = '') { const candidate = fallbackCrest(name, side); const folder = side === 'away' ? 'team-away' : 'team-home'; const homeIndex = Number(avoidHome.match(/team-home-(\d+)\.png$/)?.[1] || 0); const blocked = new Set(VISUALLY_DUPLICATE_AWAY_BY_HOME[homeIndex] || []); const allowed = (path: string) => !used.has(path) && !blocked.has(Number(path.match(/-(\d+)\.png$/)?.[1] || 0)); if (allowed(candidate)) return candidate; for (let i = 1; i <= 20; i += 1) { const next = `/admin-logos/${folder}-${String(i).padStart(2, '0')}.png`; if (allowed(next)) return next; } return candidate; }
export function ensureDistinctMatchLogos(matches: MatchRow[]) { const homeUsed = new Set<string>(); const awayUsed = new Set<string>(); return matches.map(match => { if (!match.isAdmin && !match.featured) return match; const homeLogo = distinctCrest(match.homeTeam, 'home', homeUsed); const awayLogo = distinctCrest(match.awayTeam, 'away', awayUsed, homeLogo); homeUsed.add(homeLogo); awayUsed.add(awayLogo); return { ...match, displayHomeLogo: homeLogo, displayAwayLogo: awayLogo }; }); }
export function normalizeMatches(payload: unknown, sport: Sport = 'football'): MatchRow[] { let rows: unknown = payload; if (rows && typeof rows === 'object' && 'data' in rows) rows = (rows as { data: unknown }).data; if (rows && typeof rows === 'object' && Array.isArray((rows as { content?: unknown[] }).content)) rows = (rows as { content: unknown[] }).content; if (rows && typeof rows === 'object' && Array.isArray((rows as { matches?: unknown[] }).matches)) rows = (rows as { matches: unknown[] }).matches; if (!Array.isArray(rows) && rows && typeof rows === 'object') { const obj = rows as Record<string, unknown>; rows = Object.values(obj).flatMap(value => Array.isArray(value) ? value : []); } if (!Array.isArray(rows)) return []; const unique = new Map<string, MatchRow>(); for (const entry of rows) { const match = normalizeMatch(entry, sport); if (!match) continue; const prior = unique.get(match.id); if (!prior || (isLiveStatus(match.status) && !isLiveStatus(prior.status)) || (match.scoreHome != null && prior.scoreHome == null)) unique.set(match.id, match); } return ensureDistinctMatchLogos(Array.from(unique.values())); }
export function sportFeedPath(sport: Sport, feed: Feed) { return feed === 'results' ? `/api/public/${sport}/matches/results?limit=50` : `/api/public/${sport}/matches/${feed}`; }
export function primaryOdds(raw: unknown, homeTeam: string, awayTeam: string) { const rows: Record<string, unknown>[] = []; const walk = (value: unknown) => { if (Array.isArray(value)) { value.forEach(walk); return; } if (!value || typeof value !== 'object') return; const obj = value as Record<string, unknown>; const selection = obj.selection ?? obj.outcome ?? obj.name ?? obj.label ?? obj.type; const odd = obj.odd ?? obj.value ?? obj.odds ?? obj.price; if (selection != null && odd != null) rows.push(obj); for (const [key, child] of Object.entries(obj)) if (['data','odds','match_result','markets','options'].includes(key)) walk(child); }; walk(raw); const norm = (value: unknown) => String(value ?? '').trim().toLowerCase(); const home = norm(homeTeam), away = norm(awayTeam); const teamMatch = (selection: string, team: string) => selection === team || selection.includes(team) || team.includes(selection); let one='', draw='', two=''; for (const row of rows) { const selection = norm(row.selection ?? row.outcome ?? row.name ?? row.label ?? row.type); const value = Number(row.odd ?? row.value ?? row.odds ?? row.price); if (!Number.isFinite(value) || value <= 1 || value > 200) continue; if (selection === '1' || selection === 'home' || teamMatch(selection, home)) one ||= value.toFixed(2); else if (selection === 'x' || selection === 'draw') draw ||= value.toFixed(2); else if (selection === '2' || selection === 'away' || teamMatch(selection, away)) two ||= value.toFixed(2); } if (!one && !draw && !two) { const values = rows.map(row => Number(row.odd ?? row.value ?? row.odds ?? row.price)).filter(value => Number.isFinite(value) && value > 1 && value < 50); if (values.length >= 2) { one = values[0].toFixed(2); if (values.length >= 3) draw = values[1].toFixed(2); two = values[values.length >= 3 ? 2 : 1].toFixed(2); } } return { homeOdds: one, drawOdds: draw, awayOdds: two }; }
export async function fetchAdminMatches(): Promise<MatchRow[]> {
  try {
    const payloads = await Promise.all([
      api<unknown>('GET', '/api/public/admin-matches').catch(() => []),
      api<unknown>('GET', '/api/public/football/matches/live').catch(() => []),
      api<unknown>('GET', '/api/public/football/matches/upcoming').catch(() => []),
    ]);
    const rows = normalizeMatches(payloads.flatMap(payload => normalizeMatches(payload, 'football')), 'football');
    const enriched = await Promise.all(rows.map(async match => {
      let odds = { homeOdds: match.homeOdds || '', drawOdds: match.drawOdds || '', awayOdds: match.awayOdds || '' };
      if (match.isAdmin || match.featured) {
        try {
          odds = { ...odds, ...primaryOdds(await api('GET', `/api/public/admin-matches/${encodeURIComponent(match.id)}/odds`), match.homeTeam, match.awayTeam) };
        } catch { /* public featured odds can be empty */ }
      }
      const homeLogo = match.displayHomeLogo || match.homeLogo || fallbackCrest(match.homeTeam, 'home');
      const awayLogo = (!match.awayLogo || match.awayLogo === homeLogo) ? fallbackCrest(match.awayTeam, 'away') : (match.displayAwayLogo || match.awayLogo);
      return { ...match, isAdmin: true, featured: true, homeLogo, awayLogo, displayHomeLogo: homeLogo, displayAwayLogo: awayLogo, ...odds };
    }));
    return enriched.filter(match => !isFinishedMatch(match)).sort((a, b) => {
      if (isLiveStatus(a.status) !== isLiveStatus(b.status)) return isLiveStatus(a.status) ? -1 : 1;
      return new Date(a.kickoffAt || 0).getTime() - new Date(b.kickoffAt || 0).getTime();
    });
  } catch {
    return [];
  }
}
export async function fetchMatchDetail(id: string, sport: Sport = 'football') { const candidates = [`/api/public/${sport}/matches/${encodeURIComponent(id)}/detail`, `/api/public/${sport}/matches/${encodeURIComponent(id)}`]; for (const path of candidates) { try { const payload = await api<unknown>('GET', path); const wrapped = payload && typeof payload === 'object' && 'match' in payload ? (payload as { match: unknown }).match : payload; const rows = normalizeMatches(Array.isArray(wrapped) ? wrapped : [wrapped], sport); if (rows[0]) return rows[0]; } catch { /* try next */ } } for (const feed of ['upcoming', 'today', 'live'] as Feed[]) { try { const rows = normalizeMatches(await api('GET', sportFeedPath(sport, feed)), sport); const found = rows.find(row => row.id === id); if (found) return found; } catch { /* try public feed fallback */ } } return null; }
export async function fetchMatchOdds(id: string, sport: Sport = 'football') { try { return await api('GET', `/api/public/${sport}/matches/${encodeURIComponent(id)}/odds/all`); } catch { try { return await api('GET', `/api/public/${sport}/matches/${encodeURIComponent(id)}/odds`); } catch { return null; } } }
export async function catalog() { return (await import('./endpoint-catalog.json')).default as Array<{ namespace: string; method: string; path: string; source_line: number }>; }
