import { useState } from 'react';

type Direction = { id: string; name: string; tag: string; className: string; summary: string };
const directions: Direction[] = [
  { id: '01', name: 'Command Center', tag: 'Balanced / sportsbook-first', className: 'detail-design-command', summary: 'A confident all-rounder: score hero above, grouped markets left, live timeline and compact stats right.' },
  { id: '02', name: 'Odds Terminal', tag: 'Trading desk / market-dense', className: 'detail-design-terminal', summary: 'Puts betting markets first with a strong odds grid, fast collapsible groups, and a persistent live score rail.' },
  { id: '03', name: 'Matchday Story', tag: 'Editorial / event-led', className: 'detail-design-story', summary: 'Makes the game feel alive: the event timeline is the visual anchor and odds sit naturally around the story.' },
  { id: '04', name: 'Live Room', tag: 'Immersive / mobile-ready', className: 'detail-design-room', summary: 'A premium live room with an oversized scoreboard, quick markets, and horizontal stat strips.' },
];
const marketGroups: Array<[string, string[]]> = [['Match result', ['Arsenal 1.18', 'Draw 6.40', 'Chelsea 12.00']], ['Half time', ['Arsenal 1.62', 'Draw 2.40', 'Chelsea 7.20']], ['Correct score', ['1:0 4.80', '2:0 6.10', '2:1 7.40', '1:1 8.20']], ['Handicap', ['Arsenal (-1.5) 2.10', 'Chelsea (+1.5) 1.72']]];
function Crest({ text, lime = false }: { text: string; lime?: boolean }) { return <span className={`detail-design-crest ${lime ? 'lime' : ''}`}>{text}</span>; }
function ScoreHero({ compact = false }: { compact?: boolean }) { return <div className={`detail-design-scorehero${compact ? ' compact' : ''}`}><div className="detail-design-league"><span className="material-symbols-rounded">emoji_events</span> Premier League · Matchday 12 <b><i /> LIVE</b></div><div className="detail-design-scoreline"><div><Crest text="ARS" /><strong>Arsenal</strong><small>HOME</small><b>2</b></div><section><small><span className="material-symbols-rounded">timer</span> 83'</small><strong>2 — 1</strong><span>Emirates Stadium</span></section><div><Crest text="CHE" lime /><strong>Chelsea</strong><small>AWAY</small><b>1</b></div></div></div>; }
function Markets({ dense = false }: { dense?: boolean }) { return <section className="detail-design-panel detail-design-markets"><div className="detail-design-panel-title"><div><small>LIVE PRICES</small><h3>Popular markets</h3></div><span>{dense ? 'All markets' : 'Updated now'}</span></div>{marketGroups.map(([title, options]) => <div className="detail-design-market" key={title}><button><b>{title}</b><span className="material-symbols-rounded">expand_more</span></button><div>{options.map(option => { const [label, value] = option.split(/ (?=[0-9])/); return <button key={option}><span>{label}</span><strong>{value}</strong></button>; })}</div></div>)}</section>; }
function Timeline() { return <section className="detail-design-panel detail-design-timeline"><div className="detail-design-panel-title"><div><small>LIVE COMMENTARY</small><h3>Match events</h3></div><span className="detail-design-live"><i /> Live</span></div>{[['83\'','sports_soccer','Goal','Arsenal · Bukayo Saka'],['61\'','style','Yellow card','Chelsea · Moisés Caicedo'],['HT','pause_circle','Half time','Arsenal lead 1 — 0']].map(([time,icon,title,desc]) => <div className="detail-design-event" key={time}><b>{time}</b><span className="material-symbols-rounded">{icon}</span><div><strong>{title}</strong><small>{desc}</small></div></div>)}</section>; }
function Stats({ strip = false }: { strip?: boolean }) { const rows = [['Possession','58%','42%'],['Shots on target','7','3'],['Corners','6','2']]; return <section className={`detail-design-panel detail-design-stats${strip ? ' strip' : ''}`}><div className="detail-design-panel-title"><div><small>GAME SNAPSHOT</small><h3>Quick stats</h3></div></div>{rows.map(([label,a,b]) => <div className="detail-design-stat" key={label}><span>{label}</span><b>{a} <em>—</em> {b}</b><i><u style={{ width: a.includes('%') ? a : '65%' }} /></i></div>)}</section>; }
function DesignPreview({ direction }: { direction: Direction }) { return <article className={`detail-design-option ${direction.className}`}><header className="detail-design-option-head"><span>{direction.id}</span><div><h2>{direction.name}</h2><p>{direction.tag}</p></div><span className="material-symbols-rounded">{direction.id === '01' ? 'dashboard' : direction.id === '02' ? 'monitoring' : direction.id === '03' ? 'auto_stories' : 'live_tv'}</span></header><div className="detail-design-canvas"><div className="detail-design-browserbar"><span>LUCKYSTAKE / MATCH DETAILS</span><small>ARS vs CHE · Live</small></div><ScoreHero compact={direction.id === '02'} />{direction.id === '01' && <div className="detail-design-two-col"><Markets /><div><Timeline /><Stats /></div></div>}{direction.id === '02' && <div className="detail-design-terminal-grid"><aside><div className="detail-design-mini-score"><Crest text="ARS" /><b>2 — 1</b><Crest text="CHE" lime /><small>83' · LIVE</small></div><Timeline /></aside><Markets dense /></div>}{direction.id === '03' && <div className="detail-design-story-grid"><Timeline /><div><Markets /><Stats /></div></div>}{direction.id === '04' && <><div className="detail-design-quickmarkets">{['1 · 1.18', 'X · 6.40', '2 · 12.00'].map(x => <button key={x}>{x}</button>)}</div><div className="detail-design-room-grid"><Stats strip /><Timeline /></div></>}<p className="detail-design-summary">{direction.summary}</p></div></article>; }
export default function MatchDetailsDesigns() { const [selected, setSelected] = useState('01'); return <section className="detail-designs-page"><div className="detail-designs-heading"><div><small>LUCKYSTAKE / MATCH DETAIL DIRECTIONS</small><h1>The game<br /><b>has a new home.</b></h1><p>Four distinct directions for the LuckyStake match-details experience. Each keeps the same real-data contract: live score, match minute, grouped odds, events, stats, team-logo fallbacks, and mobile responsiveness.</p></div><div className="detail-designs-select">{directions.map(d => <button key={d.id} className={selected === d.id ? 'active' : ''} onClick={() => setSelected(d.id)}><b>{d.id}</b><span>{d.name}</span></button>)}</div></div><div className="detail-design-selected">{directions.filter(d => d.id === selected).map(d => <DesignPreview direction={d} key={d.id} />)}</div><div className="detail-designs-all">{directions.filter(d => d.id !== selected).map(d => <button key={d.id} onClick={() => setSelected(d.id)}><b>{d.id}</b><span>{d.name}</span><small>{d.tag}</small><span className="material-symbols-rounded">arrow_forward</span></button>)}</div></section>; }
