import { useState } from 'react';

type Market = { title: string; icon: string; category: string; values: Array<[string, string]> };
const markets: Market[] = [
  { category: 'CORE', title: 'Match Result', icon: 'sports_soccer', values: [['Arsenal', '1.18'], ['Draw', '6.40'], ['Chelsea', '12.00']] },
  { category: 'CORE', title: 'Half Time', icon: 'schedule', values: [['Arsenal', '1.62'], ['Draw', '2.40'], ['Chelsea', '7.20']] },
  { category: 'SCORE', title: 'Correct Score', icon: 'scoreboard', values: [['1:0', '4.80'], ['2:0', '6.10'], ['2:1', '7.40'], ['1:1', '8.20'], ['0:0', '10.00'], ['3:1', '11.50']] },
  { category: 'LINES', title: 'Handicap', icon: 'compare_arrows', values: [['Arsenal (-1.5)', '2.10'], ['Chelsea (+1.5)', '1.72'], ['Arsenal (-0.5)', '1.34'], ['Chelsea (+0.5)', '3.05']] },
  { category: 'GOALS', title: 'Total Goals', icon: 'filter_9_plus', values: [['Over 1.5', '1.10'], ['Under 1.5', '5.80'], ['Over 2.5', '1.42'], ['Under 2.5', '2.70']] },
  { category: 'GOALS', title: 'Both Teams To Score', icon: 'done_all', values: [['Yes', '1.67'], ['No', '2.05']] },
];
const designs = [
  { id: '01', name: 'Neon Slip', tag: 'High contrast / fastest betting', cls: 'mobile-odds-neon' },
  { id: '02', name: 'Stacked Pro', tag: 'Dense / professional / familiar', cls: 'mobile-odds-stacked' },
  { id: '03', name: 'Glass Markets', tag: 'Premium / airy / expressive', cls: 'mobile-odds-glass' },
  { id: '04', name: 'Compact Grid', tag: 'Maximum scan / minimum scroll', cls: 'mobile-odds-grid' },
];
function Crest({ label, lime = false }: { label: string; lime?: boolean }) { return <span className={`mobile-odds-crest${lime ? ' lime' : ''}`}>{label}</span>; }
function Phone({ cls }: { cls: string }) { const [open, setOpen] = useState<string>('Match Result'); const [selected, setSelected] = useState(''); return <div className={`mobile-odds-phone ${cls}`}><div className="mobile-odds-notch" /><div className="mobile-odds-screen"><div className="mobile-odds-nav"><button><span className="material-symbols-rounded">arrow_back</span></button><b>Match odds</b><button><span className="material-symbols-rounded">more_vert</span></button></div><div className="mobile-odds-fixture"><small>PREMIER LEAGUE · LIVE</small><div><span><Crest label="ARS" /><b>Arsenal</b></span><strong>2 — 1<em>83'</em></strong><span><Crest label="CHE" lime /><b>Chelsea</b></span></div></div><div className="mobile-odds-livebar"><i /> Prices update live <span>▾</span></div><div className="mobile-odds-category-row">{['CORE', 'SCORE', 'LINES', 'GOALS'].map(category => <span key={category}>{category}</span>)}</div><div className="mobile-odds-list">{markets.map(market => <section className={`mobile-odds-market${open === market.title ? ' open' : ''}`} key={market.title}><button className="mobile-odds-market-head" onClick={() => setOpen(open === market.title ? '' : market.title)}><span><span className="material-symbols-rounded">{market.icon}</span><b>{market.title}</b><small>{market.category} · {market.values.length} selections</small></span><span className="material-symbols-rounded">{open === market.title ? 'remove' : 'add'}</span></button>{open === market.title && <div className="mobile-odds-options">{market.values.map(([label, value]) => <button className={selected === `${market.title}-${label}` ? 'selected' : ''} key={label} onClick={() => setSelected(`${market.title}-${label}`)}><span>{label}</span><b>{value}</b></button>)}</div>}</section>)}</div><div className="mobile-odds-bottom"><span><span className="material-symbols-rounded">receipt_long</span> Bet slip <b>{selected ? '1' : '0'}</b></span><button>View slip <span className="material-symbols-rounded">arrow_forward</span></button></div></div></div>; }
export default function MobileOddsPreviews() { return <section className="mobile-odds-page"><div className="mobile-odds-heading"><div><small>LUCKYSTAKE / MOBILE ODDS-ONLY PREVIEW</small><h1>Four ways to<br /><b>read the odds.</b></h1><p>All four mobile directions are shown together for a direct comparison. Each one keeps the fixture context, categorizes the markets, and makes every odds card clear, selectable, and bet-slip ready.</p></div><div className="mobile-odds-legend"><span><i className="legend-core" /> Core markets</span><span><i className="legend-score" /> Score markets</span><span><i className="legend-lines" /> Lines & goals</span></div></div><div className="mobile-odds-showcase">{designs.map(design => <article className="mobile-odds-design-card" key={design.id}><div className="mobile-odds-design-meta"><b>{design.id}</b><div><h2>{design.name}</h2><small>{design.tag}</small></div></div><Phone cls={design.cls} /></article>)}</div><div className="mobile-odds-category-explainer"><span className="material-symbols-rounded">view_list</span><div><b>Every market is categorized</b><small>CORE for primary outcomes, SCORE for exact results, LINES for handicap/spreads, and GOALS for totals and both-teams-to-score.</small></div></div></section>; }
